baseURL = "https://arkaprabhachakraborty.github.io/"
languageCode = "en-us"
title = "Arkaprabha Chakraborty"
copyright = "© ArkaprabhaChakraborty"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji = true

[params]
	mode = "toggle"
    og_image = "https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
	useCDN = true
    favicon = "https://images.assetsdelivery.com/compings_v2/uasumy/uasumy1503/uasumy150300032.jpg" 
    sitename = "Arka's Personal website"
    description = "Arkaprabha Chakraborty's Personal Website"


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ArkaprabhaChakraborty"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/FValkyrie_17"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/ArkaprabhaChakraborty"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/arkaprabhachakraborty/"



# Main menu Items

[[menu.main]]
name = "Blogs"
url = "/blog/all_of_my_blogs"
weight = 2

[[menu.main]]
name = "Projects"
url = "/posts"
weight = 3