name = "Anubis2"
license = "MIT"
licenselink = "https://github.com/Junyi-99/hugo-theme-anubis2/blob/master/LICENSE"
description = "A minimal and elegant Hugo theme"
homepage = "https://github.com/Junyi-99/hugo-theme-anubis2"
demosite = "https://hugo-theme-anubis2.netlify.app/"
tags = [
    "blog",
    "responsive",
    "personal",
    "minimal",
    "clean",
    "simple",
    "light",
    "dark",
    "google-analytics",
    "mobile",
    "fast",
    "multilingual"
]
features = ["blog"]

[author]
    name = "Junyi"
    homepage = "https://www.junyi.dev/"
